services:
  mongo:
    image: mongo:latest
    container_name: studysathi
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - dbdata6:/data/lib

volumes:
  dbdata6:
